### ISSUE TITLE
Feature Request Time-Bias

### ISSUE THREAD

**Issue by my4n6** [Fetchered/time_decode#11]
Hi Corey,

may I ask you for integrating an optional feature? It would be nice to set a time bias, i.e. you want the result converted in utc +XX instead of utc, like the Time Zone Adjustment-Field in Dcode from Digital Detective?

A very nice project by the way! It is very helpfull :-)

Regards

Stefan B. (my4n6)

**Comment by digitalsleuth** [comment]
Hi Stefan! Absolutely this is something I can work into the program. Out of curiosity, are you looking for more when converting from a date/time to a timestamp, or vice versa?

**Comment by my4n6** [comment]
Hi Corey! Nice 👍 By converting from date/time to a timestamp special format, i.e. LE 32 Bit HEX values, it might be possible to detect Timestamps in unknown data structures where I am expecting timestamp to be present. This could be a database or a pretty poor documented file system :-).  
The time bias might come in to place when I have get data from foreign countries (timezones) and I do have to find evidence in my countries data. And I remember a database where I had to add or subtract a certain value from the decimal timestamp to get the unix epoch value.

**Comment by digitalsleuth** [comment]
Hi Stefan, currently you can use the timezone to convert a date/time value to a timestamp by simply adding the numerical interpretation after the value. For example: `time-decode --timestamp "2024-01-24 20:24:22 -5"` and it will convert that timezone to the appropriate timestamp. However, it doesn't currently work from timestamp to date/time with the timezone. That part I'll work on.

**Comment by digitalsleuth** [comment]
Hi Stefan, I haven't forgotten about this, just haven't had much time lately to work on it. I'll definitely be putting more work into it over the coming weeks for the GUI portion of it.

**Comment by digitalsleuth** [comment]
Hi @my4n6 , I've gotten to a beta phase with the next version of Time Decode, which will include the ability to modify input and output timestamps with different time zones. I'd appreciate another set of eyes for testing before a release, so let me know if you're interested and willing to provide some feedback.

Cheers!

**Comment by digitalsleuth** [comment]
Hi @my4n6 , I've added the newest version, 8.0.0, which has the option to select both to encode a date/time with timezone into a timestamp, and to decode a timestamp to a date/time in a certain timezone.

Cheers!

**Comment by my4n6** [comment]
Hello Corey, sure. I am a little bit busy, but I will check it out in the next days.
Cheers!
