### ISSUE TITLE
Feature Request: NSDate

### ISSUE THREAD

**Issue by randomaccess3** [Fetchered/time_decode#3]
nsdate time format, seen on iOS 

import datetime
nsdate = 540790206.087728
unixTS = 978307200
final = nsdate + unixTS
date = str(datetime.datetime.fromtimestamp(final))
print (date)

**Comment by Fetchered** [comment]
Hi Phil,

This timestamp is already available in the tool, as iostime.

Have you tried that option already? If not, give it a shot and let me know
if that's what you're looking for.

Cheers

Corey

**Comment by randomaccess3** [comment]
Yeah, it's user error im sure

python time_decode.py --ios "540790206.087728"
ERROR:root:<class 'TypeError'>,must be str, not bool

**Comment by Fetchered** [comment]
Let me take a look and get back to you.

**Comment by Fetchered** [comment]
BTW, what's the actual date and time you're expecting so I can compare
results?

**Comment by Fetchered** [comment]
The timestamp format in iOS is either a Mac Absolute Time (9-digit) or iOS
nanosecond date (18 digit). The value you gave me isn't a full 18 digit
(since it's separated by a decimal) but the first 9 are the Mac Absolute
Timestamp of 2018-02-20 03:30:06 UTC.

**Comment by randomaccess3** [comment]
it's taken from an nsdate field within a plist (within another plist within an sqlite database, because apple...)
the mac absolute timestamp you posted looks right

**Comment by Fetchered** [comment]
Any chance you're able to tell me the names of the plists and sqlite files
so I can do some research? And is it possible that value you gave might be
missing some digits?

The way the two timestamps appear in iOS, there shouldn't be a separator
(such as the dot), so if it exists in these files, I'll have to have a
reference to see why it might be there, and since the Absolute value is
correct, it's possible the value after the dot is for something else.

Hope you're able to provide the references. I'll keep looking into it.

**Comment by randomaccess3** [comment]
yep, inside the knowledgeC database on an iOS device (file system extraction), there's an embedded plist within an embedded plist.
Inside that there's nsdate fields.

decoding of the dates can be found at the bottom of this
https://github.com/cclgroupltd/ccl-bplist/blob/master/ccl_bplist.py

**Comment by Fetchered** [comment]
I happen to have that already. I'll look into it and get it sorted. Thanks!

**Comment by Fetchered** [comment]
So, the ccl_bplist essentially is taking the first 9 characters (the Mac
Absolute Time) and converting that to the first piece of the timestamp, and
the values after the decimal are the milliseconds/nanoseconds.
Using the first 9 digits will give the correct time in time_decode.py down
to the second, but I will add a feature in the next release to read/convert
the bplist timestamp to include those milli/nanos.

In the meantime, the tool should still work for what you need. When you
convert your value using the Mac Absolute, just use the value after the
decimal as your milli/nano seconds.

I'll try to get the update done this weekend.

Cheers

**Comment by randomaccess3** [comment]
Great, thanks!

**Comment by Fetchered** [comment]
Updated the tool, should work the way you expect now. I appreciate the
feedback btw!
