### ISSUE TITLE
Feature Request / Volunteer : Graphical Window (Stay-on-top)

### ISSUE THREAD

**Issue by ghost** [Fetchered/time_decode#4]
New Repo to rework into a Graphical display (single file, PyQt5)? Any complaints or comments for this?

**Comment by Fetchered** [comment]
Been thinking about this, and will be working on it in the future.

If you wish to volunteer to help with this, I wouldn’t mind the assistance.

 

My thinking is a simple two-box, one-text field window. Text field shows decoded/encoded value, first box is a drop-down selector for timestamp type (or choose Guess/Convert To All), second is an entry field to supply value or date.

If required based on choice (Guess/Convert), the text field will be large enough to show all possible values.

 

Am planning on making this GUI multi-platform, so must work well in Windows/Linux/Mac environments, and also not opposed to the idea of releasing separate compilations for each OS type.

 

We can discuss this offline if that’s good for you. You can drop me a line on gmail, address is my github repo.

**Comment by ghost** [comment]
OK. I pulled it last night. Reworked all the functions down to based and removed argparse.  I then reworked it, did a basic PyQt5 build GUI, easily multi-platform.

Most of it is up and running, broke a couple of things in the process when I was linking it up earlier, but should be easily solved. Is this kind of what you had in mind?

![time_decode_img1](https://user-images.githubusercontent.com/41962217/57633472-a3b7d980-7571-11e9-92e4-aa287d7d45f5.png)

![time_decode_img2](https://user-images.githubusercontent.com/41962217/57633477-a5819d00-7571-11e9-8c5f-f6d0a37936d9.png)

**Comment by Fetchered** [comment]
Pretty much. Do you have it uploaded so I can check it out?

**Comment by Raylorman** [comment]
Sent invite, you need link or you good?
